import os
from pathlib import Path
import stat
import shutil
import sys
import zipfile
import psutil
#Dependencies found from:
#1.Formatted output from cmd command: tasklist /m /FO CSV /NH /fi "imagename eq amberol.exe"
#Formatted by replacing all commas with: ",\n"
#And manually placing a double quote at start of the first element and end of the last, along with their corresponding square bracket.
#2. The same, just as it processed files added to playlist.
#3. Trial and error. Using all files with "pixbuf" in their basename was found through trial and error - needed to load images. Check which explicitly removes .exe files was only to remove files with "pixbuf" in their names, but .exe as well, which we do not want.
dependencies = ["amberol.exe",
"5636",
"ntdll.dll",
"KERNEL32.DLL",
"KERNELBASE.dll",
"bcrypt.dll",
"msvcrt.dll",
"ADVAPI32.dll",
"libadwaita-1-0.dll",
"libcairo-gobject-2.dll",
"sechost.dll",
"libcairo-2.dll",
"GDI32.dll",
"RPCRT4.dll",
"win32u.dll",
"libdbus-1-3.dll",
"libgdk_pixbuf-2.0-0.dll",
"gdi32full.dll",
"WS2_32.dll",
"msvcp_win.dll",
"ucrtbase.dll",
"ole32.dll",
"USER32.dll",
"libglib-2.0-0.dll",
"SHELL32.dll",
"libgio-2.0-0.dll",
"libgobject-2.0-0.dll",
"libgraphene-1.0-0.dll",
"SHLWAPI.dll",
"libgstaudio-1.0-0.dll",
"libgstbase-1.0-0.dll",
"libgstplayer-1.0-0.dll",
"combase.dll",
"libgstvideo-1.0-0.dll",
"libgstreamer-1.0-0.dll",
"libintl-8.dll",
"libgtk-4-1.dll",
"libpango-1.0-0.dll",
"USERENV.dll",
"libfribidi-0.dll",
"libgcc_s_seh-1.dll",
"gdiplus.dll",
"IPHLPAPI.DLL",
"MSIMG32.dll",
"libfontconfig-1.dll",
"libfreetype-6.dll",
"libpixman-1-0.dll",
"libpng16-16.dll",
"zlib1.dll",
"libpcre2-8-0.dll",
"libstdc++-6.dll",
"DNSAPI.dll",
"libffi-8.dll",
"libgmodule-2.0-0.dll",
"liborc-0.4-0.dll",
"libgsttag-1.0-0.dll",
"libgstplay-1.0-0.dll",
"comdlg32.dll",
"shcore.dll",
"libwinpthread-1.dll",
"libiconv-2.dll",
"libharfbuzz-0.dll",
"CRYPT32.dll",
"libthai-0.dll",
"IMM32.dll",
"SETUPAPI.dll",
"cfgmgr32.dll",
"libexpat-1.dll",
"libbz2-1.dll",
"libbrotlidec.dll",
"libgstpbutils-1.0-0.dll",
"COMCTL32.dll",
"dwmapi.dll",
"USP10.dll",
"libgraphite2.dll",
"HID.DLL",
"libdatrie-1.dll",
"WINMM.dll",
"WINSPOOL.DRV",
"libcairo-script-interpreter-2.dll",
"libepoxy-0.dll",
"libjpeg-8.dll",
"libpangocairo-1.0-0.dll",
"libpangowin32-1.0-0.dll",
"libtiff-6.dll",
"libbrotlicommon.dll",
"liblzo2-2.dll",
"libpangoft2-1.0-0.dll",
"DWrite.dll",
"libdeflate.dll",
"libjbig-0.dll",
"libLerc.dll",
"liblzma-5.dll",
"libwebp-7.dll",
"libzstd.dll",
"DPAPI.DLL",
"libsharpyuv-0.dll",
"NSI.dll",
"CRYPTBASE.DLL",
"bcryptPrimitives.dll",
"windows.storage.dll",
"Wldp.dll",
"libgstaccurip.dll",
"libgstadder.dll",
"libgstadpcmdec.dll",
"libgstadpcmenc.dll",
"libgstaes.dll",
"libcrypto-3-x64.dll",
"libgstaiff.dll",
"libgstalaw.dll",
"libgstalpha.dll",
"libgstalphacolor.dll",
"libgstaom.dll",
"libaom.dll",
"libgstapetag.dll",
"libgstapp.dll",
"libgstapp-1.0-0.dll",
"libgstasfmux.dll",
"libgstrtp-1.0-0.dll",
"libgstassrender.dll",
"libass-9.dll",
"libunibreak-5.dll",
"libgstaudiobuffersplit.dll",
"libgstaudioconvert.dll",
"libgstaudiofx.dll",
"libgstfft-1.0-0.dll",
"libgstaudiofxbad.dll",
"libgstaudiolatency.dll",
"libgstaudiomixer.dll",
"libgstaudiomixmatrix.dll",
"libgstaudioparsers.dll",
"libgstaudiorate.dll",
"libgstaudioresample.dll",
"libgstaudiotestsrc.dll",
"libgstaudiovisualizers.dll",
"libgstauparse.dll",
"libgstautoconvert.dll",
"libgstautodetect.dll",
"libgstavi.dll",
"libgstriff-1.0-0.dll",
"libgstbayer.dll",
"libgstbs2b.dll",
"libgstbz2.dll",
"libgstcacasink.dll",
"libcaca-0.dll",
"libgstcairo.dll",
"libgstcamerabin.dll",
"libgstphotography-1.0-0.dll",
"libgstbasecamerabinsrc-1.0-0.dll",
"libgstchromaprint.dll",
"libchromaprint.dll",
"libgstclosedcaption.dll",
"libgstcodecalpha.dll",
"libgstcoloreffects.dll",
"libgstcolormanagement.dll",
"liblcms2-2.dll",
"libgstcompositor.dll",
"libgstcoreelements.dll",
"libgstcoretracers.dll",
"libgstcurl.dll",
"libcurl-4.dll",
"WLDAP32.dll",
"libnghttp2-14.dll",
"libpsl-5.dll",
"libidn2-0.dll",
"libssh2-1.dll",
"libssl-3-x64.dll",
"libunistring-2.dll",
"libgstcutter.dll",
"libgstd3d.dll",
"d3d9.dll",
"kernel.appcore.dll",
"libgstd3d11.dll",
"dxgi.dll",
"libgstcodecs-1.0-0.dll",
"libgstcontroller-1.0-0.dll",
"libgstcodecparsers-1.0-0.dll",
"libgstd3d11-1.0-0.dll",
"d3d11.dll",
"d3dcompiler_47.dll",
"CRYPTSP.dll",
"apphelp.dll",
"dxcore.dll",
"uxtheme.dll",
"libgstdash.dll",
"libgstadaptivedemux-1.0-0.dll",
"libgstisoff-1.0-0.dll",
"libxml2-2.dll",
"libgstnet-1.0-0.dll",
"libgsturidownloader-1.0-0.dll",
"libgstdebug.dll",
"libgstdebugutilsbad.dll",
"libgstdecklink.dll",
"OLEAUT32.dll",
"libgstdeinterlace.dll",
"libgstdirectsound.dll",
"DSOUND.dll",
"winmmbase.dll",
"powrprof.dll",
"UMPDC.dll",
"libgstdirectsoundsrc.dll",
"libgstdtls.dll",
"libgstdtmf.dll",
"libgstdtsdec.dll",
"libdca-0.dll",
"libgstdvbsubenc.dll",
"libgstdvbsuboverlay.dll",
"libgstdvdspu.dll",
"libgsteffectv.dll",
"libgstencoding.dll",
"libgstequalizer.dll",
"libgstfaac.dll",
"libfaac-0.dll",
"libgstfaad.dll",
"libfaad-2.dll",
"libgstfaceoverlay.dll",
"libgstfdkaac.dll",
"libfdk-aac-2.dll",
"libgstfestival.dll",
"libgstfieldanalysis.dll",
"libgstflac.dll",
"libFLAC.dll",
"libogg-0.dll",
"libgstfluidsynthmidi.dll",
"libfluidsynth-3.dll",
"libreadline8.dll",
"libportaudio.dll",
"libgomp-1.dll",
"libtermcap-0.dll",
"libsndfile-1.dll",
"SDL2.dll",
"libopus-0.dll",
"libvorbis-0.dll",
"libvorbisenc-2.dll",
"VERSION.dll",
"libgstflv.dll",
"libgstflxdec.dll",
"libgstfreeverb.dll",
"libgstfrei0r.dll",
"libgstgaudieffects.dll",
"libgstgdkpixbuf.dll",
"libgstgdp.dll",
"libgstgeometrictransf",
"amberol.exe",
"796",
"ntdll.dll",
"KERNEL32.DLL",
"KERNELBASE.dll",
"bcrypt.dll",
"libadwaita-1-0.dll",
"msvcrt.dll",
"libcairo-gobject-2.dll",
"libcairo-2.dll",
"ADVAPI32.dll",
"GDI32.dll",
"libgdk_pixbuf-2.0-0.dll",
"libdbus-1-3.dll",
"sechost.dll",
"win32u.dll",
"WS2_32.dll",
"RPCRT4.dll",
"gdi32full.dll",
"ole32.dll",
"ucrtbase.dll",
"msvcp_win.dll",
"libgio-2.0-0.dll",
"SHELL32.dll",
"libglib-2.0-0.dll",
"combase.dll",
"USER32.dll",
"SHLWAPI.dll",
"libgobject-2.0-0.dll",
"libgraphene-1.0-0.dll",
"libgstplayer-1.0-0.dll",
"libgstaudio-1.0-0.dll",
"libgstbase-1.0-0.dll",
"libgstreamer-1.0-0.dll",
"libgstvideo-1.0-0.dll",
"libgtk-4-1.dll",
"libintl-8.dll",
"libfribidi-0.dll",
"libpango-1.0-0.dll",
"USERENV.dll",
"comdlg32.dll",
"libgcc_s_seh-1.dll",
"IPHLPAPI.DLL",
"shcore.dll",
"gdiplus.dll",
"CRYPT32.dll",
"IMM32.dll",
"SETUPAPI.dll",
"DNSAPI.dll",
"cfgmgr32.dll",
"libgmodule-2.0-0.dll",
"libpcre2-8-0.dll",
"libstdc++-6.dll",
"zlib1.dll",
"libfontconfig-1.dll",
"MSIMG32.dll",
"libpixman-1-0.dll",
"libpng16-16.dll",
"libfreetype-6.dll",
"libffi-8.dll",
"libgstplay-1.0-0.dll",
"liborc-0.4-0.dll",
"libgsttag-1.0-0.dll",
"libwinpthread-1.dll",
"libiconv-2.dll",
"libharfbuzz-0.dll",
"libthai-0.dll",
"COMCTL32.dll",
"HID.DLL",
"dwmapi.dll",
"libcairo-script-interpreter-2.dll",
"WINMM.dll",
"libepoxy-0.dll",
"WINSPOOL.DRV",
"libpangocairo-1.0-0.dll",
"libjpeg-8.dll",
"libpangowin32-1.0-0.dll",
"libtiff-6.dll",
"libexpat-1.dll",
"libbz2-1.dll",
"libbrotlidec.dll",
"libgstpbutils-1.0-0.dll",
"libgraphite2.dll",
"libdatrie-1.dll",
"USP10.dll",
"liblzo2-2.dll",
"libpangoft2-1.0-0.dll",
"libdeflate.dll",
"libjbig-0.dll",
"DWrite.dll",
"libLerc.dll",
"libwebp-7.dll",
"liblzma-5.dll",
"libzstd.dll",
"libbrotlicommon.dll",
"DPAPI.DLL",
"libsharpyuv-0.dll",
"NSI.dll",
"CRYPTBASE.DLL",
"bcryptPrimitives.dll",
"windows.storage.dll",
"Wldp.dll",
"mswsock.dll",
"fwpuclnt.dll",
"rasadhlp.dll",
"libgstplayback.dll",
"libgstaudiofx.dll",
"libgstfft-1.0-0.dll",
"libgstreplaygain.dll",
"libgstvolume.dll",
"winhttp.dll",
"kernel.appcore.dll",
"uxtheme.dll",
"clbcatq.dll",
"AppXDeploymentClient.dll",
"Windows.ApplicationModel.dll",
"OLEAUT32.dll",
"twinapi.appcore.dll",
"propsys.dll",
"profapi.dll",
"apphelp.dll",
"NetworkExplorer.dll",
"MPR.dll",
"p9np.dll",
"drprov.dll",
"WINSTA.dll",
"ntlanman.dll",
"davclnt.dll",
"DAVHLPR.dll",
"mssprxy.dll",
"mrmcorer.dll",
"iertutil.dll",
"windows.staterepositorycore.dll",
"bcp47mrm.dll",
"Windows.UI.dll",
"InputHost.dll",
"TextInputFramework.dll",
"WindowManagementAPI.dll",
"CoreUIComponents.dll",
"CoreMessaging.dll",
"wintypes.dll",
"ntmarta.dll",
"libmedia-gstreamer.dll",
"libgstgl-1.0-0.dll",
"OPENGL32.dll",
"GLU32.dll",
"KBDUS.DLL",
"MSCTF.dll",
"directmanipulation.dll",
"DEVOBJ.dll",
"WINTRUST.dll",
"MSASN1.dll",
"libgstcoreelements.dll",
"libpixbufloader-svg.dll",
"libxml2-2.dll",
"librsvg-2-2.dll",
"dataexchange.dll",
"d3d11.dll",
"dcomp.dll",
"dxgi.dll",
"atig6pxx.dll",
"atio6axx.dll",
"VERSION.dll",
"dxva2.dll",
"atig6txx.dll",
"atiadlxx.dll",
"PSAPI.DLL",
"dxcore.dll",
"libEGL.dll",
"libGLESv2.dll",
"d3d9.dll",
"wshunix.dll",
"WindowsCodecs.dll",
"DUI70.dll",
"DUser.dll",
"TextShaping.dll",
"edputil.dll",
"thumbcache.dll",
"policymanager.dll",
"msvcp110_win.dll",
"StructuredQuery.dll",
"atlthunk.dll",
"Windows.Storage.Search.dll",
"Windows.FileExplorer.Common.dll",
"EhStorShell.dll",
"Windows.StateRepositoryPS.dll",
"wkscli.dll",
"cscapi.dll",
"netutils.dll",
"dlnashext.dll",
"PlayToDevice.dll",
"DevDispItemProvider.dll",
"MMDevApi.dll",
"ntshrui.dll",
"SspiCli.dll",
"srvcli.dll",
"wpdshext.dll",
"PortableDeviceApi.dll",
"PortableDeviceTypes.dll",
"EhStorAPI.dll",
"WTSAPI32.dll",
"Ninput.dll",
"libgstaudioconvert.dll",
"libgstlevel.dll",
"libgsttypefindfunctions.dll",
"libgstaudioparsers.dll",
"libgstwasapi.dll",
"libgstflac.dll",
"libFLAC.dll",
"libogg-0.dll",
"AUDIOSES.DLL",
"powrprof.dll",
"UMPDC.dll",
"resourcepolicyclient.dll",
"libgstaudioresample.dll",
"avrt.dll",
"libpixbufloader-jpeg.dll",
"libgstid3demux.dll",
"libgstmpg123.dll",
"libmpg123-0.dll"]

fileLoadDependencies = ['5636', 'SDL2.dll', 'libgstd3ibgstdash.dll', 'libgstflv.dll', 'libgstflxdec.dll', 'libgstfreeverb.dll', 'libgstfrei0r.dll', 'libgstgaudieffects.dll', 'libgstgdkpixbuf.dll', 'libgstgdp.dll', 'libgstgeometrictransf', 'libopus-0.dll', 'libsndfile-1.dll', 'libvorbis-0.dll', 'libvorbisenc-2.dll']

for dependency in fileLoadDependencies:
    dependencies.append(dependency)

for dependency in ["io-wmf.dll", "loaders.cache","gdk-pixbuf-thumbnailer.thumbnailer", "dbus-daemon.exe", "org.gtk.GLib.PACRunner.service", "session.conf" ]: #manual finds
    dependencies.append(dependency)

amberolMinDir = os.path.join(os.getcwd(), "amberol")
originalAmberolDir = os.path.join(os.getcwd(), "amberol-compile-env")
amberolZipPath = os.path.join(os.getcwd(),"amberol.zip")
if not os.path.exists(originalAmberolDir):
    input("No Amberol directory to prune! Press enter to exit. >")
    sys.exit()

def remove_readonly(func, path, excinfo): #In case of failed attempt to remove read-only file or folder.
    os.chmod(path, stat.S_IRWXU)
    func(path)

def kill_processes():
    for proc in psutil.process_iter():
        if proc.name() in ["dbus-daemon.exe", "amberol.exe"]:
            print("Killing process:", proc.name())
            proc.kill()

def ignore_files(path, filenames):
    ignoredFiles = []
    for file_name in filenames:
        file_path = os.path.join(path, file_name)
        if not(file_name in dependencies or "libpixbufloader" in file_name or str(Path("bin/amberol")) in str(file_path) or os.path.isdir(file_path)):
            ignoredFiles.append(file_name)
    if ignoredFiles == []:
        print("Skipped directory:", path)
    return ignoredFiles

def copy_file(src,dst):
    print("Copying file:", src, "to: ", dst)
    return shutil.copy2(src=src,dst=dst)

def setup_directory():
    if os.path.exists(amberolMinDir) and os.path.isdir(amberolMinDir) and "--wipe" in sys.argv:
        print("Deleting:",amberolMinDir)
        shutil.rmtree(amberolMinDir, onerror=remove_readonly)
        print("Done.")
    if not os.path.exists(amberolMinDir) or not os.path.isdir(amberolMinDir):
        print("Copying compile environment to amberol folder...")
        shutil.copytree(src=originalAmberolDir, dst=amberolMinDir, dirs_exist_ok=True, symlinks=True, ignore=ignore_files, copy_function=copy_file)
        print("Done.")
    if os.path.exists(amberolZipPath):
        ("Removing: ",amberolZipPath)
        os.chmod(mode=stat.S_IWRITE, path=amberolZipPath)
        os.remove(os.path.join(os.getcwd(),amberolZipPath))
        print("Done.")

def delete_empty_folders():
    print("Removing empty directories...")
    for root, dirnames, filenames in os.walk(amberolMinDir, topdown=False):
        for dirname in dirnames:
            directory = os.path.join(root,dirname)
            if os.path.isdir(directory) and not os.listdir(directory):
                print("Removing directory:", directory)
                shutil.rmtree(directory,onerror=remove_readonly)

def zip_files():
    print("Zipping amberol directory for release...")
    zip_file = zipfile.ZipFile(file=amberolZipPath, mode='w', compression=zipfile.ZIP_DEFLATED, compresslevel=9)
    for path in (Path(amberolMinDir).rglob(('*'))):
        print("Zipping:", str(path), "to:", str(amberolZipPath)+str(path).replace(os.getcwd(),''))
        zip_file.write(arcname=Path(str(path).replace(os.getcwd(),'')), filename=path)
    print("Done.")

#Not used - symlinks do not work for launching .exes on Windows
def create_symlink():
    print("Generating symlink...")
    if os.path.isfile(os.path.join(amberolMinDir,"run_amberol")):
        print("Deleting symlink")
        os.remove(os.path.join(amberolMinDir,"run_amberol"))
    print("Creating symlink")
    os.chdir(amberolMinDir)
    os.symlink(src=Path("./bin/amberol.exe"),dst=Path("./run_amberol"))
    os.chdir(Path(".."))
    print("Done.")

kill_processes()
setup_directory()
delete_empty_folders()
# create_symlink()
zip_files()
print("") #Skips line for readability
# The window will disappear as soon as the program exits otherwise
input("Complete! Press enter to exit. >")
